### ISSUE TITLE
京东登录未判断有验证码情况

### ISSUE THREAD

**Issue by ruicky** [xuess/nightmare-sign#2]
如题， 在京东登录的时候，我这边有验证码，但是没有自动识别输入，是否加入相关代码？
![](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fu3lzwldcmj308y0fwgmn.jpg)

**Comment by clampist** [comment]
same as ruicky, maybe should hack it

**Comment by xuess** [comment]
@ruicky @clampist  暂时没有办法解决。。。。
