### ISSUE TITLE
京东会员签到无效

### ISSUE THREAD

**Issue by ZZ250-zZ** [xuess/nightmare-sign#4]
![image](https://user-images.githubusercontent.com/26135265/58076770-a358b780-7bdd-11e9-8de1-fd872759834f.png)
学习大佬的代码ing，此处无法触发。改为 .click('.react-view.sign-in-pop .react-view img') 依旧无效，不是click事件？还是找错了？

**Comment by xuess** [comment]
估计他们改版了。近期准备重写。
