### ISSUE TITLE
这个可以部署云函数上吗？测试了一下好像不行

### ISSUE THREAD

**Issue by Mark-1215** [xuess/nightmare-sign#5]
{"errorCode":-1,"errorMessage":"Error: Cannot find module 'node-schedule'\n    at Function.Module._resolveFilename (module.js:538:15)\n    at Function.Module._load (module.js:468:25)\n    at Module.require (module.js:587:17)\n    at require (internal/module.js:11:18)\n    at Object.\u003canonymous\u003e (/var/user/index.js:1:80)\n    at Module._compile (module.js:643:30)\n    at Object.Module._extensions..js (module.js:654:10)\n    at Module.load (module.js:556:32)\n    at tryModuleLoad (module.js:499:12)\n    at Function.Module._load (module.js:491:3)"}

日志:

START RequestId: f9b0bd1c-9d8a-46ad-a460-825d5214847f

Event RequestId: f9b0bd1c-9d8a-46ad-a460-825d5214847f

 

ERROR RequestId:f9b0bd1c-9d8a-46ad-a460-825d5214847f Result:{"errorCode":-1,"errorMessage":"Error: Cannot find module 'node-schedule'\n    at Function.Module._resolveFilename (module.js:538:15)\n    at Function.Module._load (module.js:468:25)\n    at Module.require (module.js:587:17)\n    at require (internal/module.js:11:18)\n    at Object.\u003canonymous\u003e (/var/user/index.js:1:80)\n    at Module._compile (module.js:643:30)\n    at Object.Module._extensions..js (module.js:654:10)\n    at Module.load (module.js:556:32)\n    at tryModuleLoad (module.js:499:12)\n    at Function.Module._load (module.js:491:3)"} 

END RequestId: f9b0bd1c-9d8a-46ad-a460-825d5214847f

Report RequestId: f9b0bd1c-9d8a-46ad-a460-825d5214847f Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by xuess** [comment]
你说的云函数是Serverless吗？ 没试过，我试试看。

**Comment by xuess** [comment]
这个工程有段时间没维护了，你试试这个工程https://github.com/xuess/puppeteer-sign  @Mark-1215
